# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_images/default.png', upload_to='recipe_images/'),
        ),
    ]
