# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotrecipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_images/default.png', upload_to='recipe_images'),
        ),
    ]
